//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// このソース コードは xsd によって自動生成されました。Version=4.8.3928.0 です。
// 
namespace Aozora.GaijiChuki.Xsd {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd", IsNullable=false)]
    public partial class dictionary {
        
        private dictionaryKanji kanjiField;
        
        private dictionaryOther otherField;
        
        /// <remarks/>
        public dictionaryKanji kanji {
            get {
                return this.kanjiField;
            }
            set {
                this.kanjiField = value;
            }
        }
        
        /// <remarks/>
        public dictionaryOther other {
            get {
                return this.otherField;
            }
            set {
                this.otherField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class dictionaryKanji {
        
        private page[] pageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("page")]
        public page[] page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd", IsNullable=false)]
    public partial class page {
        
        private pageRadical radicalField;
        
        private entry[] entriesField;
        
        /// <remarks/>
        public pageRadical radical {
            get {
                return this.radicalField;
            }
            set {
                this.radicalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public entry[] entries {
            get {
                return this.entriesField;
            }
            set {
                this.entriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class pageRadical {
        
        private pageRadicalReadings readingsField;
        
        private pageRadicalCharacters charactersField;
        
        /// <remarks/>
        public pageRadicalReadings readings {
            get {
                return this.readingsField;
            }
            set {
                this.readingsField = value;
            }
        }
        
        /// <remarks/>
        public pageRadicalCharacters characters {
            get {
                return this.charactersField;
            }
            set {
                this.charactersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class pageRadicalReadings {
        
        private string[] readingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reading")]
        public string[] reading {
            get {
                return this.readingField;
            }
            set {
                this.readingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd", IsNullable=false)]
    public partial class entry {
        
        private entryCharacters charactersField;
        
        private object itemField;
        
        private note noteField;
        
        private entryUCV[] uCVField;
        
        private string refPageField;
        
        private string docPageField;
        
        private string strokesField;
        
        private bool duplicateField;
        
        private entrySupplement supplementField;
        
        private bool supplementFieldSpecified;
        
        public entry() {
            this.refPageField = "0";
            this.docPageField = "0";
            this.duplicateField = false;
            this.supplementField = entrySupplement.@default;
        }
        
        /// <remarks/>
        public entryCharacters characters {
            get {
                return this.charactersField;
            }
            set {
                this.charactersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Compatible78Inclusion", typeof(entryCompatible78Inclusion))]
        [System.Xml.Serialization.XmlElementAttribute("designVariant", typeof(entryDesignVariant))]
        [System.Xml.Serialization.XmlElementAttribute("inclusionApplication", typeof(entryInclusionApplication))]
        [System.Xml.Serialization.XmlElementAttribute("inputable", typeof(object))]
        [System.Xml.Serialization.XmlElementAttribute("integrationApplication", typeof(entryIntegrationApplication))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public note note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UCV")]
        public entryUCV[] UCV {
            get {
                return this.uCVField;
            }
            set {
                this.uCVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string refPage {
            get {
                return this.refPageField;
            }
            set {
                this.refPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string docPage {
            get {
                return this.docPageField;
            }
            set {
                this.docPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string strokes {
            get {
                return this.strokesField;
            }
            set {
                this.strokesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool duplicate {
            get {
                return this.duplicateField;
            }
            set {
                this.duplicateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        [System.ComponentModel.DefaultValueAttribute(entrySupplement.@default)]
        public entrySupplement supplement {
            get {
                return this.supplementField;
            }
            set {
                this.supplementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool supplementSpecified {
            get {
                return this.supplementFieldSpecified;
            }
            set {
                this.supplementFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class entryCharacters {
        
        private string[] characterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("character")]
        public string[] character {
            get {
                return this.characterField;
            }
            set {
                this.characterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class entryCompatible78Inclusion {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class entryDesignVariant {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @ref {
            get {
                return this.refField;
            }
            set {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class entryInclusionApplication {
        
        private object itemField;
        
        private entryInclusionApplicationReference[] referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("character", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("note", typeof(note))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reference")]
        public entryInclusionApplicationReference[] reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd", IsNullable=false)]
    public partial class note {
        
        private string preField;
        
        private string fullField;
        
        private string descriptionField;
        
        private object itemField;
        
        /// <remarks/>
        public string pre {
            get {
                return this.preField;
            }
            set {
                this.preField = value;
            }
        }
        
        /// <remarks/>
        public string full {
            get {
                return this.fullField;
            }
            set {
                this.fullField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("jisx0213", typeof(noteJisx0213))]
        [System.Xml.Serialization.XmlElementAttribute("unicode", typeof(noteUnicode))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class noteJisx0213 {
        
        private int levelField;
        
        private bool levelFieldSpecified;
        
        private int menField;
        
        private bool menFieldSpecified;
        
        private int kuField;
        
        private bool kuFieldSpecified;
        
        private int tenField;
        
        private bool tenFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool levelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int men {
            get {
                return this.menField;
            }
            set {
                this.menField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool menSpecified {
            get {
                return this.menFieldSpecified;
            }
            set {
                this.menFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ku {
            get {
                return this.kuField;
            }
            set {
                this.kuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool kuSpecified {
            get {
                return this.kuFieldSpecified;
            }
            set {
                this.kuFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ten {
            get {
                return this.tenField;
            }
            set {
                this.tenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tenSpecified {
            get {
                return this.tenFieldSpecified;
            }
            set {
                this.tenFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class noteUnicode {
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class entryInclusionApplicationReference {
        
        private string pageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class entryIntegrationApplication {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("character", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("note", typeof(note))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class entryUCV {
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public enum entrySupplement {
        
        /// <remarks/>
        supplementOnly,
        
        /// <remarks/>
        supplementCommon,
        
        /// <remarks/>
        @default,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class pageRadicalCharacters {
        
        private string[] characterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("character")]
        public string[] character {
            get {
                return this.characterField;
            }
            set {
                this.characterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class dictionaryOther {
        
        private PageOther[] pageOtherField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PageOther")]
        public PageOther[] PageOther {
            get {
                return this.pageOtherField;
            }
            set {
                this.pageOtherField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd", IsNullable=false)]
    public partial class PageOther {
        
        private string headerField;
        
        private PageOther[] pageOther1Field;
        
        private PageOtherEntry[] entriesField;
        
        /// <remarks/>
        public string header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PageOther")]
        public PageOther[] PageOther1 {
            get {
                return this.pageOther1Field;
            }
            set {
                this.pageOther1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public PageOtherEntry[] entries {
            get {
                return this.entriesField;
            }
            set {
                this.entriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://github.com/kurema/AozoraGaijiChukiXml/blob/master/data/Chuki.xsd")]
    public partial class PageOtherEntry {
        
        private string characterField;
        
        private note noteField;
        
        private string infoField;
        
        private string docPageField;
        
        private bool inputableField;
        
        public PageOtherEntry() {
            this.docPageField = "0";
            this.inputableField = false;
        }
        
        /// <remarks/>
        public string character {
            get {
                return this.characterField;
            }
            set {
                this.characterField = value;
            }
        }
        
        /// <remarks/>
        public note note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
        
        /// <remarks/>
        public string info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        [System.ComponentModel.DefaultValueAttribute("0")]
        public string docPage {
            get {
                return this.docPageField;
            }
            set {
                this.docPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool inputable {
            get {
                return this.inputableField;
            }
            set {
                this.inputableField = value;
            }
        }
    }
}
